# Generated by Django 3.0.8 on 2020-07-10 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('version', models.CharField(max_length=8, verbose_name='Version')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='machine',
            name='address',
            field=models.GenericIPAddressField(null=True, protocol='IPV4', validators=[django.core.validators.validate_ipv4_address]),
        ),
        migrations.AddField(
            model_name='machine',
            name='environment',
            field=models.CharField(choices=[('DEV', 'Development'), ('PROD', 'Production'), ('QA', 'Quality Assurance'), ('TEST', 'Test')], default='DEV', max_length=30, verbose_name='Enviroment'),
        ),
        migrations.AddField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='machine',
            name='operation_systems',
            field=models.ManyToManyField(to='log_api.OperationSystem'),
        ),
    ]
