# Generated by Django 3.0.8 on 2020-07-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_api', '0002_auto_20200710_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='App-Name', max_length=50, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='application',
            name='version',
            field=models.CharField(max_length=8, null=True, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='operationsystem',
            name='installed_apps',
            field=models.ManyToManyField(to='log_api.Application'),
        ),
    ]
