# Generated by Django 3.0.8 on 2020-07-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_api', '0003_auto_20200715_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='operation_systems',
        ),
        migrations.AddField(
            model_name='machine',
            name='applications',
            field=models.ManyToManyField(to='log_api.Application'),
        ),
        migrations.DeleteModel(
            name='OperationSystem',
        ),
    ]
