# Generated by Django 3.0.8 on 2020-07-14 03:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log_api', '0003_auto_20200710_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='event',
            name='dateref',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='DateRef'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='test', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='execution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='log_api.Execution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('DEBUG', 'DEBUG'), ('WARNING', 'WARNING'), ('INFO', 'INFO')], default='INFO', max_length=20, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='execution',
            name='application_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_execution', to='log_api.Application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='execution',
            name='dateref',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='DateRef'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='execution',
            name='machine_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='machine_execution', to='log_api.Machine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='execution',
            name='success',
            field=models.BooleanField(default=True, verbose_name='Success'),
            preserve_default=False,
        ),
    ]
