# Generated by Django 3.0.8 on 2020-07-20 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_api', '0004_auto_20200715_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='machine_id',
        ),
        migrations.AddField(
            model_name='execution',
            name='environment',
            field=models.CharField(choices=[('DEV', 'Development'), ('PROD', 'Production'), ('QA', 'Quality Assurance'), ('TEST', 'Test')], default='DEV', max_length=30, verbose_name='Enviroment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='execution_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='log_api.Execution'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='application_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='log_api.Application'),
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
