# Generated by Django 3.0.8 on 2020-07-14 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_api', '0005_auto_20200714_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='execution',
        ),
        migrations.AddField(
            model_name='event',
            name='execution_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='execution_id', to='log_api.Execution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='dateref',
            field=models.DateTimeField(verbose_name='DateRef'),
        ),
    ]
