# Generated by Django 3.0.8 on 2020-07-29 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_api', '0006_auto_20200728_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='machine_id',
        ),
        migrations.AddField(
            model_name='execution',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executions', to='log_api.Application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='execution',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='execution',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='executions', to='log_api.Machine'),
            preserve_default=False,
        ),
    ]
