# Generated by Django 3.0.8 on 2020-07-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_api', '0007_auto_20200728_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='success',
            field=models.BooleanField(null=True, verbose_name='Success'),
        ),
    ]
